/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.testes.rafael.telas;

import br.com.testes.rafael.dao.DBConnectionMySql1;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTextField;
import javax.swing.JLabel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Rafa
 */
public class JifCadastro extends javax.swing.JInternalFrame {
    Connection connection = DBConnectionMySql1.getConnection();
    /**
     * Creates new form JifCadastro
     */
    public JifCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JtfNome = new javax.swing.JTextField();
        JtfMatricula = new javax.swing.JTextField();
        JtfCHora = new javax.swing.JTextField();
        JtfCHora.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		JtfCHora.setText("");
        	}
        });
        JtfCHora.setText("Ex: 00:00:00");
        BtnCadastrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de novos Funcionarios ");

        jLabel1.setText("Nome:");

        jLabel2.setText("Numero da Matricula:");

        jLabel3.setText("Carga horaria:");

        JtfMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfMatriculaActionPerformed(evt);
            }
        });

        BtnCadastrar.setText("Cadastrar");
        BtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarActionPerformed(evt);
            }
        });
        
        JtfSalario = new JTextField();
        JtfSalario.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		JtfSalario.setText("");
        	}
        });
        JtfSalario.setText("Ex: 100,00");
        JtfSalario.setColumns(10);
        
        JLabel lblSalario = new JLabel("Salario:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addGap(92)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(lblSalario)
        				.addComponent(JtfMatricula, GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        				.addComponent(jLabel2)
        				.addComponent(JtfNome, GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        				.addComponent(jLabel1)
        				.addComponent(jLabel3)
        				.addComponent(JtfCHora, GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        				.addComponent(JtfSalario))
        			.addContainerGap(97, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(147, Short.MAX_VALUE)
        			.addComponent(BtnCadastrar)
        			.addGap(135))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(JtfNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jLabel2)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(JtfMatricula, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jLabel3)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(JtfCHora, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(lblSalario)
        			.addGap(4)
        			.addComponent(JtfSalario, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(BtnCadastrar)
        			.addGap(109))
        );
        getContentPane().setLayout(layout);

        setBounds(250, 20, 379, 396);
    }// </editor-fold>//GEN-END:initComponents

    private void JtfMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfMatriculaActionPerformed

    private void BtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarActionPerformed
        String nome = JtfNome.getText();
        String matricula = JtfMatricula.getText();
        String hora = JtfCHora.getText();
        String salario = JtfSalario.getText();
        
        try {
		//Aplicacoes estabelecermos a conexao com o banco de dados
		//Utilizamos o metodo createStatement de con para criar o Statement  
		//Statement stm = connection.createStatement();       
		PreparedStatement pstn = connection.prepareStatement(
                        "INSERT INTO funcionarios(id_matricula,nome,carga_horaria,salario) VALUES ('"+ matricula+ "','"+ nome+ "','"+ hora+ "','"+salario+"');");
		
		//Vamos executar o seguinte comando SQL:  
		 int result = pstn.executeUpdate();
			
		if (result == 1){
					 
                    JOptionPane.showMessageDialog(null,"Os dados foram inseridos com sucesso ");
						 
                    JtfNome.setText("");
                    JtfMatricula.setText("");
                    JtfCHora.setText("");
                    JtfSalario.setText("");
		 }

		} catch (SQLException e1) {
		// se houve algum erro, uma excecao e gerado para informar o erro
		// vejamos que erro foi gerado e quem o gerou
		e1.printStackTrace();
		JOptionPane.showMessageDialog(null,
			"Houve um erro durante a conexao com o banco de dados.\nErro: "
			+ e1.getMessage(), "erro de conexao", JOptionPane.ERROR_MESSAGE);
	
		} finally {
			DBConnectionMySql1.close();
			System.out.println("Fechamento da conexao OK");
		} // fim do bloco try-catch-finally              
    }//GEN-LAST:event_BtnCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadastrar;
    private javax.swing.JTextField JtfCHora;
    private javax.swing.JTextField JtfMatricula;
    private javax.swing.JTextField JtfNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private JTextField JtfSalario;
}
