/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.testes.rafael.telas;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JMenuItem;
import javax.swing.ImageIcon;
import javax.swing.KeyStroke;
import java.awt.event.KeyEvent;
import java.awt.event.InputEvent;
import javax.swing.JSeparator;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;

/**
 *
 * @author Rafa
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpprincipal = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        BtnCadastro = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        BtnPesquisa = new javax.swing.JButton();
        BtnIArquivo = new javax.swing.JButton();
        JSeparator4 = new javax.swing.JToolBar.Separator();
        BtnPesquisa.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		
        		JifFiltro obj = new JifFiltro();
                jdpprincipal.add(obj); 
                obj.setVisible(true);
        	}
        });
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpprincipalLayout = new javax.swing.GroupLayout(jdpprincipal);
        jdpprincipalLayout.setHorizontalGroup(
        	jdpprincipalLayout.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 745, Short.MAX_VALUE)
        );
        jdpprincipalLayout.setVerticalGroup(
        	jdpprincipalLayout.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 436, Short.MAX_VALUE)
        );
        jdpprincipal.setLayout(jdpprincipalLayout);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator1);

        BtnCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Clientes.png"))); // NOI18N
        BtnCadastro.setFocusable(false);
        BtnCadastro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCadastro.setMaximumSize(new java.awt.Dimension(60, 45));
        BtnCadastro.setMinimumSize(new java.awt.Dimension(60, 45));
        BtnCadastro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastroActionPerformed(evt);
            }
        });
        jToolBar1.add(BtnCadastro);
        jToolBar1.add(jSeparator2);

        BtnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/listapedidos.png"))); // NOI18N
        BtnPesquisa.setFocusable(false);
        BtnPesquisa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnPesquisa.setMaximumSize(new java.awt.Dimension(60, 45));
        BtnPesquisa.setMinimumSize(new java.awt.Dimension(60, 45));
        BtnPesquisa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(BtnPesquisa);

        jMenu1.setText("Cadastro");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Clientes.png"))); // NOI18N
        jMenuItem1.setText("Cadastro de novos Funcionarios ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        
        BtnIArquivo.setIcon(new ImageIcon(Principal.class.getResource("/Imagens/uploads.png"))); // NOI18N
        BtnIArquivo.setFocusable(false);
        BtnIArquivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnIArquivo.setMaximumSize(new java.awt.Dimension(60, 45));
        BtnIArquivo.setMinimumSize(new java.awt.Dimension(60, 45));
        BtnIArquivo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnIArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	BtnIArquivoActionPerformed(evt);
            }
        });
        jToolBar1.add(JSeparator4);
        
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);
        
        mntmInserirNovoArquivo = new JMenuItem("Inserir novo arquivo Txt");
        mntmInserirNovoArquivo.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		
        		JifInserirTxt obj = new JifInserirTxt();
                jdpprincipal.add(obj); 
                obj.setVisible(true);
        	}
        });
        mntmInserirNovoArquivo.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_T, InputEvent.ALT_MASK));
        mntmInserirNovoArquivo.setIcon(new ImageIcon(Principal.class.getResource("/Imagens/uploads.png")));
        jMenu1.add(mntmInserirNovoArquivo);

        jMenu2.setText("Navegar");
        jMenuBar1.add(jMenu2);
        
        mntmFiltroDeHoras = new JMenuItem("Filtro de Horas");
        mntmFiltroDeHoras.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		
        		JifFiltro obj = new JifFiltro();
        		jdpprincipal.add(obj); 
        	    obj.setVisible(true);
        	}
        });
        mntmFiltroDeHoras.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F, InputEvent.ALT_MASK));
        mntmFiltroDeHoras.setIcon(new ImageIcon(Principal.class.getResource("/Imagens/listapedidos2.png")));
        jMenu2.add(mntmFiltroDeHoras);

        jMenu3.setText("Arquivos");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
            .addComponent(jdpprincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdpprincipal))
        );
        jToolBar1.add(BtnIArquivo);

        setBounds(0, 0, 761, 547);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

    JifCadastro obj = new JifCadastro();
    jdpprincipal.add(obj); 
    obj.setVisible(true);

    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void BtnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastroActionPerformed
        
        JifCadastro obj = new JifCadastro();
        jdpprincipal.add(obj); 
        obj.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_BtnCadastroActionPerformed 
    
    private void BtnIArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastroActionPerformed
        
        JifInserirTxt obj = new JifInserirTxt();
        jdpprincipal.add(obj); 
        obj.setVisible(true);
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadastro;
    private javax.swing.JButton BtnPesquisa;
    private javax.swing.JButton BtnIArquivo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator JSeparator3;
    private javax.swing.JToolBar.Separator JSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDesktopPane jdpprincipal;
    private JMenuItem mntmFiltroDeHoras;
    private JMenuItem mntmInserirNovoArquivo;
}
